CLASS LHC_ZZREPLYCODE_R DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEREPLYCODEUUID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  ZZREPLYCODE_R~CalculateReplyCodeUUID .
ENDCLASS.

CLASS LHC_ZZREPLYCODE_R IMPLEMENTATION.
  METHOD CALCULATEREPLYCODEUUID.
  ENDMETHOD.
ENDCLASS.
